# -*- coding: utf-8 -*-
"""Day 1 Assignment Solution - Hrutikesh Sawant

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gohz9YzzDk-od9Xb19U3OtE8MnwmWqfe

# Day 1 Assignment Solution

## To sort list in Descending order
"""

numbers = [40, 79, 45, 56, 38]
numbers.sort(reverse = True)
print(numbers)